---
title: "Proteomics"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: true
layout: page
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("here")) {install.packages("here"); require("here")}
if (!require("readxl")) {install.packages("readxl"); require("readxl")}
if (!require("pheatmap")) {install.packages("pheatmap"); require("pheatmap")}
if (!require("tibble")) {install.packages("tibble"); require("tibble")}
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")}
if (!require("writexl")) {install.packages("writexl"); require("writexl")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("kableExtra")) {install.packages("kableExtra"); require("kableExtra")}
```


# List of Proteomic Datasets

[Four Core Genotype](#FourCoreGenotype) <br>
[PT ACE2 KO](#PTACE2KO) <br>

<a id="FourCoreGenotype"></a>

# Four Core Genotype

*Description here.*

## Heatmap of dataframe

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=12, fig.width=6}

#load data
FCG <- read_excel("dataset/FCG.xlsx")
FCG <- FCG %>% column_to_rownames("Protein")

#make heat map
palette_blues <- colorRampPalette(colors = c("#4575B4", "#91BFDB", "#E0F3F8", "white", "#FEE090", "#FEE090", "#FEE090", "#FC8D59","#FC8D59", "#FC8D59", "#FC8D59", "#D73027", "#D73027", "#D73027", "#D73027"))(100)

f1 <- pheatmap(FCG , cluster_rows = FALSE, cluster_cols = FALSE, scale = "none",show_rownames = TRUE, show_colnames = TRUE, main = "Heatmap of Kidney Transporter Abundance", angle_col = 315, fontsize_col = 10, fontsize = 10, fontsize_row = 10, color = palette_blues)

f1
```

## Table of dataframe

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=10, fig.width=3}

kable(head(FCG, n = nrow(FCG))) %>%
  kable_styling(position = "center")
```

## Link to download

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=15, fig.width=6}

# add protein column 
FCG_data <- FCG %>% rownames_to_column("Protein")

# make downloadable link
if (!dir.exists("raw data")) dir.create("raw data")
write.xlsx(FCG_data, file = "raw data/FCG_data.xlsx")
```

[Download FCG data](raw data/FCG_data.xlsx)

<a id="PTACE2KO"></a>

# PT ACE2 KO

*Description here.*

## Heatmap of dataframe

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=10, fig.width=5}

#load data
PT_ACE2_KO <- read_excel("dataset/PT ACE2 KO.xlsx")
PT_ACE2_KO <- PT_ACE2_KO %>% column_to_rownames("Protein")

palette_blues <- colorRampPalette(colors = c("#5A2A82","#7239AC","#5C4BAF","#4575B4", "#91BFDB", "#9ECAE1", "#C6DBEF", "#E0F3F8", "white", "#FEE090", "#FEE090", "#FEE090", "#FC8D59","#FC8D59", "#FC8D59", "#FC8D59"))(100)

#"#08306B", "#084594", "#08519C", "#2171B5", "#4575B4","#4292C6","#6BAED6","#91BFDB"

#make heat map
f2 <- pheatmap(PT_ACE2_KO , cluster_rows = FALSE, cluster_cols = FALSE, scale = "none", 
         show_rownames = TRUE, show_colnames = TRUE, main = "Heatmap", angle_col = 315, fontsize_col = 10, fontsize = 10, fontsize_row = 10, color = palette_blues)

f2
```

## Table of dataframe

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=10, fig.width=3}

kable(head(PT_ACE2_KO, n = nrow(PT_ACE2_KO))) %>%
  kable_styling(position = "center")
```

## Link to download

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.height=15, fig.width=6}

# add protein column 
PT_ACE2_KO_data <- PT_ACE2_KO %>% rownames_to_column("Protein")

# make downloadable link
if (!dir.exists("raw data")) dir.create("raw data")
write.xlsx(FCG_data, file = "raw data/PT_ACE2_KO_data.xlsx")
```

[Download PT ACE2 KO data](raw data/PT_ACE2_KO_data.xlsx)

